### ISSUE TITLE
About the pytorch version

### ISSUE THREAD

**Issue by dmortem** [yaodi833/NeuTraj#1]
Hi, @yaodi833 
Thank you for your codes! I want to ask you about the pytorch version you use. Currently I use python 2.7 and Pytorch0.1.12, but I met an error "RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1501972792122/work/pytorch-0.1.12/torch/lib/THC/THCGeneral.c:66" when send the variable to cuda.

Thanks a lot!

**Comment by yaodi833** [comment]
Sorry for the late reply. My pytorch version is 0.4.1.

**Comment by dmortem** [comment]
Thanks! I will try again!
